---
source_path: "/ftp/client/TYPE1/PRV2TECHNO2/{{ filter_day | regex_replace('^(\\d\\d\\d\\d)(\\d\\d)(\\d\\d)$', '\\3\\2\\1') }}"
dst_path: /home/type1_provider2_techno2/flat_file
tmp_root: /ftp/client/TYPE1/PRV2TECHNO2/flat_file
prv2_techno2_filter:
  - RLOUVJA
expected_hourly_files: 4
expected_daily_files: 96
