---
version: '2'

services:
  bastion:
    image: ${REGISTRY}/bastion:${STABLE_VERSION}
    build:
      context: ../bastion
      args:
        VERSION: ${STABLE_VERSION}
    networks:
      - type1_network
      - type2_network
      - external_network

  regulator:
    image: ${REGISTRY}/regulator:${STABLE_VERSION}
    build:
      context: ../regulator
      args:
        VERSION: ${STABLE_VERSION}
    networks:
      type1_network:
      type2_network:

  type1_provider1_src:
    image: ${REGISTRY}/simple_bastion/type1_provider1_src:${CURRENT_VERSION}
    build:
      context: ssh_src_server/
      args:
        VERSION: ${STABLE_VERSION}
        TO_DATE: ${TO_DATE}
        FROM_DATE: ${FROM_DATE}
        SCRIPT: type1_provider1.sh
    networks:
      type1_network:
        aliases:
          - type1_provider1_techno1_src

  type1_provider1_dst:
    image: ${REGISTRY}/simple_bastion/app_server:${CURRENT_VERSION}
    build:
      context: app_server/
      args:
        VERSION: ${STABLE_VERSION}
    networks:
      type1_network:
        aliases:
          - type1_provider1_techno1_dst

  type1_provider2_src:
    image: ${REGISTRY}/simple_bastion/type1_provider2_src:${CURRENT_VERSION}
    build:
      context: ssh_src_server/
      args:
        VERSION: ${STABLE_VERSION}
        TO_DATE: ${TO_DATE}
        FROM_DATE: ${FROM_DATE}
        SCRIPT: type1_provider2.sh
    networks:
      type1_network:
        aliases:
          - type1_provider2_techno1_src
          - type1_provider2_techno2_src
          - type1_provider2_techno3_src

  type1_provider2_dst:
    image: ${REGISTRY}/simple_bastion/app_server:${CURRENT_VERSION}
    build:
      context: app_server/
      args:
        VERSION: ${STABLE_VERSION}
    networks:
      type1_network:
        aliases:
          - type1_provider2_techno1_dst
          - type1_provider2_techno2_dst
          - type1_provider2_techno3_dst

  type2_provider1_src:
    image: ${REGISTRY}/simple_bastion/type2_provider1_src:${CURRENT_VERSION}
    build:
      context: ssh_src_server/
      args:
        VERSION: ${STABLE_VERSION}
        TO_DATE: ${TO_DATE}
        FROM_DATE: ${FROM_DATE}
        SCRIPT: type2_provider1.sh
    networks:
      type2_network:
        aliases:
          - type2_provider1_techno1_src
          - type2_provider1_techno2_src
          - type2_provider1_techno3_src

  type2_provider1_dst:
    image: ${REGISTRY}/simple_bastion/app_server:${CURRENT_VERSION}
    build:
      context: app_server/
      args:
        VERSION: ${STABLE_VERSION}
    networks:
      type2_network:
        aliases:
          - type2_provider1_techno1_dst
          - type2_provider1_techno2_dst
          - type2_provider1_techno3_dst

  type2_provider2_src:
    image: ${REGISTRY}/simple_bastion/type2_provider2_src:${CURRENT_VERSION}
    build:
      context: ssh_src_server/
      args:
        VERSION: ${STABLE_VERSION}
        TO_DATE: ${TO_DATE}
        FROM_DATE: ${FROM_DATE}
        SCRIPT: type2_provider2.sh
    networks:
      type2_network:
        aliases:
          - type2_provider2_techno1_src
          - type2_provider2_techno2_src
          - type2_provider2_techno3_src

  type2_provider2_dst:
    image: ${REGISTRY}/simple_bastion/app_server:${CURRENT_VERSION}
    build:
      context: app_server/
      args:
        VERSION: ${STABLE_VERSION}
    networks:
      type2_network:
        aliases:
          - type2_provider2_techno1_dst
          - type2_provider2_techno2_dst
          - type2_provider2_techno3_dst

networks:
  external_network:
  type1_network:
  type2_network:
