---
source_path: "/ftp/client/type2/PRV1TECHNO2/"
dst_path: /home/client_provider1_techno2/flat_file
tmp_root: /ftp/client/type2/PRV1TECHNO2/flat_file
expected_hourly_files: 3
expected_daily_files: 72
