---
- name: Allow nodes to synchronize between them
  shell: >
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
    creates="~/.ssh/id_rsa"

- name: Fetch the keyfile from the node to master
  fetch:
    src: "~/.ssh/id_rsa.pub"
    dest: "/tmp/{{ inventory_hostname }}-id_rsa.pub"
    flat: true

- name: Authorize other nodes to ssh
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file','/tmp/{{item}}-id_rsa.pub') }}"
  when: item != inventory_hostname
  with_items:
    - "{{ group }}"
