---
version: '2.4'

services:
  first_bastion:
    image: ${REGISTRY}first_bastion:${CURRENT_VERSION}
    build:
      context: ../bastion
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
    networks:
      - external_network
      - tra_network

  second_bastion:
    image: ${REGISTRY}second_bastion:${CURRENT_VERSION}
    build:
      context: ../bastion
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
        USER: 'usr1'
        PORT: '22'
    networks:
      - type1_network
      - type2_network
      - type3_network
      - tra_network

  regulator:
    image: ${REGISTRY}regulator:${STABLE_VERSION}
    build:
      context: ../regulator
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
    networks:
      regulator_network:

  type1_provider1_src:
    image: ${REGISTRY}double_bastion/type1_provider1_src:${CURRENT_VERSION}
    build:
      context: ssh_src_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
        TO_DATE: ${TO_DATE}
        FROM_DATE: ${FROM_DATE}
        SCRIPT: type1_provider1.sh
    networks:
      type1_network:
        aliases:
          - type1_provider1_techno1_src
          - type1_provider1_techno2_src

  type1_provider1_dst:
    image: ${REGISTRY}double_bastion/app_server:${CURRENT_VERSION}
    build:
      context: app_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
    networks:
      type1_network:
        aliases:
          - type1_provider1_techno1_dst
          - type1_provider1_techno2_dst

  type2_provider1_src:
    image: ${REGISTRY}double_bastion/type2_provider1_src:${CURRENT_VERSION}
    build:
      context: ssh_src_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
        TO_DATE: ${TO_DATE}
        FROM_DATE: ${FROM_DATE}
        SCRIPT: type2_provider1.sh
    networks:
      type2_network:
        aliases:
          - type2_provider1_techno1_src
          - type2_provider1_techno2_src

  type2_provider1_dst:
    image: ${REGISTRY}double_bastion/app_server:${CURRENT_VERSION}
    build:
      context: app_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
    networks:
      type2_network:
        aliases:
          - type2_provider1_techno1_dst
          - type2_provider1_techno2_dst

  type2_provider2_src:
    image: ${REGISTRY}double_bastion/type2_provider2_src:${CURRENT_VERSION}
    build:
      context: ssh_src_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
        TO_DATE: ${TO_DATE}
        FROM_DATE: ${FROM_DATE}
        SCRIPT: type2_provider2.sh
    networks:
      type2_network:
        aliases:
          - type2_provider2_techno1_src
          - type2_provider2_techno2_src

  type2_provider2_dst:
    image: ${REGISTRY}double_bastion/app_server:${CURRENT_VERSION}
    build:
      context: app_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
    networks:
      type2_network:
        aliases:
          - type2_provider2_techno1_dst
          - type2_provider2_techno2_dst

  type1_provider2_src:
    image: ${REGISTRY}double_bastion/type1_provider2_src:${CURRENT_VERSION}
    build:
      context: ssh_src_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
        TO_DATE: ${TO_DATE}
        FROM_DATE: ${FROM_DATE}
        SCRIPT: type1_provider2.sh
    networks:
      type1_network:
        aliases:
          - type1_provider2_techno1_src
          - type1_provider2_techno2_src

  type1_provider2_dst:
    image: ${REGISTRY}double_bastion/app_server:${CURRENT_VERSION}
    build:
      context: app_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
    networks:
      type1_network:
        aliases:
          - type1_provider2_techno1_dst
          - type1_provider2_techno2_dst

  type3_provider1_src:
    image: ${REGISTRY}double_bastion/type3_provider1_src:${CURRENT_VERSION}
    build:
      context: ssh_src_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
        TO_DATE: ${TO_DATE}
        FROM_DATE: ${FROM_DATE}
        SCRIPT: type3_provider1.sh
    networks:
      type3_network:
        aliases:
          - type3_provider1_techno1_src
          - type3_provider1_techno2_src

  type3_provider1_dst:
    image: ${REGISTRY}double_bastion/app_server:${CURRENT_VERSION}
    build:
      context: app_server/
      args:
        REGISTRY: ${REGISTRY}
        VERSION: ${STABLE_VERSION}
    networks:
      type3_network:
        aliases:
          - type3_provider1_techno1_dst
          - type3_provider1_techno2_dst

networks:
  type1_network:
  regulator_network:
  type2_network:
  type3_network:
  tra_network:
  external_network:
